function [p,desc] = GenericProperties( type, varargin )

%% Generates generic properties for CAD components. The types are:
%
%   'thermal'
%      'absorptivity','emissivity','heatGeneratedOn','heatGeneratedStandby',
%      'temperature','surfaceArea','uNormal','thermalMass'
%   'power'
%      'powerStandby', 'powerOn','electricalConversionEfficiency',
%      'powerHeater','powerIsOn'
%   'optical'
%      'sigmaT', 'sigmaA', 'sigmaD', 'sigmaS'
%   'infrared'
%      'sigmaRT', 'sigmaRA', 'sigmaRD', 'sigmaRS'
%   'mass'
%      'mass', 'cM', 'inertia'
%   'aero'
%      'cD'
%   'rF'
%      'flux', 'u', 'r'
%   'magnetic'
%      'dipole'
%   'propulsion'
%      'thrust' 'iSP' 'feedPressure' 'efficiency'
%   'graphics'
%      'faceColor' 'edgeColor' 'specularStrength' 'diffuseStrength' 
%      'ambientStrength'
%      'specularColorReflectance' 'specularExponent'
%
% You can customize properties by adding property/value pairs.
% Type GenericProperties to have a list describing the properties printed to
% the command window.
%--------------------------------------------------------------------------
%   Form:
%   p = GenericProperties( type, varargin )
%--------------------------------------------------------------------------
%
%   ------
%   Inputs
%   ------
%   type           (1,:)   Type
%
%   -------
%   Outputs
%   -------
%   p              (1,1)  Properties data structure
%   desc            {:}   Descriptions of the properties
%
%--------------------------------------------------------------------------

%--------------------------------------------------------------------------
%   Copyright (c) 2001-2003 Princeton Satellite Systems, Inc.
%   All rights reserved.
%--------------------------------------------------------------------------
%   Since version 5.5 (2003)
%--------------------------------------------------------------------------

if (nargin == 0)
  disp('List of generic component properties:')
  disp('-------------------------------------')
  types = ListAllTypes;
  for k = 1:length(types)
    fprintf(1,'-- %s ---------------------------\n',types{k});
    [p, desc] = GenericProperties(types{k});
    f = fieldnames( p );
    for j = 1:length(f)
      fprintf(1,'%20s\t%s\n',f{j},desc{j});
    end
  end

  clear p
  return;
end

if( nargin > 1 )
  n = length(varargin)/2;

  if( floor(n) ~= n )
    MessageQueue('add', 'GenericProperies','You have not entered property/value pairs','error');
	  p = [];
	  return;
  end
  for k = 1:n
	  f{k} = varargin{2*k-1};
	  v(k) = varargin{2*k};
  end
  input = 1;
else
  input = 0;
end

p = [];

switch lower(type)
  case 'thermal'
    p = struct( 'absorptivity', 0.1, 'emissivity', 0.8, 'heatGeneratedOn', 0,...
    'heatGeneratedStandby', 0, 'temperature', 300, 'surfaceArea',1, 'uNormal',[0;0;1],...
    'thermalMass',1 );
    % archived format:
    %p = struct( 'alpha', 0.1, 'epsilon', 0.8, 'heatGeneratedOn', 0, 'heatGeneratedStandby', 0, 'temperature', 300 );
    desc = {...
            'Absorptivity of the surface, between 0 and 1',...
            'Emissivity of the surface',...
            'Heat generated by the component when it is on',...
            'Heat generated when the component is on standby',...
            'Nominal temperature (K)',...
            'Surface area exposed to external flux (m2)',...
            'Normal vector of the area',...
            'Thermal mass of the component'};

  case 'power'
    p = struct( 'powerStandby', 0, 'powerOn', 0, 'electricalConversionEfficiency', 0,...
                'powerHeater', 0, 'powerIsOn',1 );
    desc = {'Power consumed when on standby (W)',...
            'Flag for commanding power to be on',...
            'Conversion efficiency for a surface',...
            'Power consumed by a heater (W)',...
            'Flag indicating is power is actually on'};

  case 'optical'
    p = struct( 'sigmaT', 0, 'sigmaA', 0.05, 'sigmaD', 0.55, 'sigmaS', 0.4 );
    desc = {'Visible spectrum transmissivity',...
            'Visible spectrum absorptivity',...
            'Visible spectrum diffuse reflectivity',...
            'Visible spectrum specular reflectivity'};

  case 'infrared'
    p = struct( 'sigmaRT', 0, 'sigmaRA', 1, 'sigmaRD', 0, 'sigmaRS', 0 );
    desc = {'Infrared transmissivity',...
            'Infrared absorptivity',...
            'Infrared diffuse reflectivity',...
            'Infrared specular reflectivity'};

  case 'mass'
    p = struct( 'mass', 0, 'cM', [0;0;0], 'inertia', zeros(3,3) );
    desc = {'Component mass (kg)',...
            'Center of mass measured from body hinge (m)',...
            'Inertia matrix about the center of mass (kg-m2)'};

  case 'aero'
    p = struct( 'cD', 2.7 );
    desc = {'Coefficient of drag'};

  case 'rf'
    p = struct( 'flux', 0, 'u', [], 'r', [] );
    desc = {'Power radiated by the antenna (W)','Unit vector of the antenna',...
      'Position of the antenna phase center ffrom the center of mass'};

  case 'magnetic'
    p = struct( 'dipole', [0;0;0] );
    desc = {'Residual magnetic dipole'};

  case 'propulsion'
    p = struct( 'thrust', 0, 'iSP', 0, 'feedPressure', 350*6895, 'efficiency', 0.0);
    desc = {'Device thrust',...
            'Specific impulse',...
            'Tank feed pressure',...
            'Device efficiency'};
	
  case 'graphics'
    p = struct( 'faceColor',[0.7 0.7 0.7], 'edgeColor', [1 1 1],...
                'diffuseStrength', 0.3, 'ambientStrength',0, 'specularStrength', 1, ...
                'specularColorReflectance',0.5, 'specularExponent', 20 );
    desc = {'Color for faces of patches, string or RGB triple',...
            'Color for edges, string or RGB triple',...
            'Diffuse strength for 3D viewing',...
            'Ambient strength for 3D viewing',...
            'Specular strength for 3D viewing',...
            '',...
            ''};

  otherwise
	  p = [];
end

if( input )
  % additional inputs passed in varargin
  for k = 1:n
	  p = setfield(p,f{k},v(k));
  end
end

%--------------------------------------------------------------------------
function types = ListAllTypes

f = [mfilename,'.m'];

[fid,msg] = fopen(f,'rt');

if( fid == -1 )
   errordlg(sprintf('Attempt to open "%s" to read list of cases failed:\n%s',f,msg));
   return;
end

types = {};

while 1
   
   t = fgetl(fid);
   
   % if end of file reached...
   if( ~ischar(t) ), break; end
   
   % if end of the list of cases reached...
   stop = strfind(t,'otherwise');
   if( ~isempty(stop) ), break; end
   
   % look for "case"
   k = strfind(t,'case');
   
   % if "case" found
   if( ~isempty(k) )
      
      % look for "%"
      p = strfind(t,'%');
      
      showLine = 1;
      
      % if "%" found
      if( ~isempty(p) )
         
         % if "%" comes before "case"
         if( p(1) < k(1) )
            
            showLine = 0;
            
         end
         
      end
      
      if( showLine )
         %disp(t(k+6:end-1));
         types{end+1} = t(k+6:end-1);
      end
      
   end
   
end

fclose(fid);


%--------------------------------------
% PSS internal file version information
%--------------------------------------
% $Date: 2016-03-18 18:04:07 -0400 (Fri, 18 Mar 2016) $
% $Revision: 41961 $
